### ISSUE TITLE
Mi unlock tool always showing this device has been activated less than 7 days
And I have waited 9 days.
Showing Error 10013

### ISSUE THREAD

**Issue by MJMonjurHossain** [RohitVerma882/termux-miunlock#11]
![Screenshot_2023-09-15-20-02-50-592_com.termux_083146.jpg](https://github.com/RohitVerma882/termux-miunlock/assets/146003357/ff71ae4d-c922-48a4-adc7-69db43753042)

My device- Redmi note 10 pro
My account is logged in on my phone
Find Me Device is turned on
Oem unlocking is turned on
Usb debugging is turned on

I want to unlock the bootloader🥺
What do I do now? 😭😭
Even though I have waited 2 times 8+9 days and I received an error ever times

**Comment by RohitVerma882** [comment]
Have you also unbounded the account from developer options before the 7 days are up?

**Comment by MJMonjurHossain** [comment]
Noo
I have followed all the official steps carefully
And today I will reset my phone and then creat a new mi account and I will try again

**Comment by MJMonjurHossain** [comment]
And in those 7 days of waiting I didn't go to developer options even once. After 7 days I tapped miui version 7 times turned on developer option and turned on OTG debugging

**Comment by MJMonjurHossain** [comment]
And in those 7 days of waiting I didn't go to developer options even once. After 7 days I tapped miui version 7 times turned on developer option and turned on OTG debugging

**Comment by davidebeatrici** [comment]
This is a not a tool issue:

![Windows](https://github.com/RohitVerma882/termux-miunlock/assets/5897523/ea6a506f-e7f2-4d5e-9fee-aa1cead5fb5a)
![Termux](https://github.com/RohitVerma882/termux-miunlock/assets/5897523/d3e75975-3030-4c38-98b7-af002eb39a67)

@MJMonjurHossain In your case the message is different, but the error code is the same.
