### ISSUE TITLE
cannot receive token or token does not appear

### ISSUE THREAD

**Issue by Aryasyamjaya** [RohitVerma882/termux-miunlock#14]
![IMG_20231007_005552](https://github.com/RohitVerma882/termux-miunlock/assets/147187395/86079e91-065c-4978-975b-f8540860c16f)

after I entered the command "mi-fastboot getvar token" the token didn't appear, please help me solve this problem, thank you🙏

**Comment by RohitVerma882** [comment]
your device cpu is qcom or mtk?

**Comment by RohitVerma882** [comment]
Command no 5 for qcom and 6 for mtk

**Comment by Aryasyamjaya** [comment]
> your device cpu is qcom or mtk?

gcom

**Comment by RohitVerma882** [comment]
Currently i don't have any solution for this error but you can try to change your host device or usb cable and try again
