### ISSUE TITLE
Showing Error

### ISSUE THREAD

**Issue by Ronyoem** [RohitVerma882/termux-miunlock#17]
Is there anything wrong or need to wait 142 hour to unlock bootloader?
@RohitVer
![Screenshot_2023-10-20-21-11-10-779_com termux](https://github.com/RohitVerma882/termux-miunlock/assets/143398497/d8b98c13-2368-4de8-8f98-a5adc2710a52)
ma882

**Comment by RohitVerma882** [comment]
need to wait 142 hour.

**Comment by RohitVerma882** [comment]
Unlocked 🔓?

**Comment by Ronyoem** [comment]
No... It’s say please use official method to unlock...then again i have to do it on mi unlock tool from pc to unlock my bootloader

**Comment by RohitVerma882** [comment]
You need to run get_token command with region option.
Like: ```./get_token.sh --region=global <DATA>```

**Comment by RohitVerma882** [comment]
See #2

**Comment by Ronyoem** [comment]
Ok thanks your tools is great... But i have already unlocked my device from pc
