### ISSUE TITLE
server returned error 20045

### ISSUE THREAD

**Issue by ahmad24shargh** [RohitVerma882/termux-miunlock#2]
Hello
Xiaomi server says: use common official tool
![Screenshot_20230813-120432_Termux](https://github.com/RohitVerma882/termux-miunlock/assets/20979212/a5050971-ef0c-49e1-8df7-9c30548b4159)

**Comment by RohitVerma882** [comment]
Try to change tool region using ```get_token.sh --region=<region> ...```

**Comment by RohitVerma882** [comment]
Use ```get_token.sh --help``` for more info

**Comment by RohitVerma882** [comment]
I have tested this tool on 1-2 devices, if it will work then also tell us.

**Comment by ahmad24shargh** [comment]
Thank you
it worked
My phone is Redmi note 12 4g with code name tapas and global ROM.
By adding
--region=global
.....
In termux, the xxd command is not installed by default. I installed it with the following command.
pkg install vim-python
....
![Screenshot_20230813-132532_Termux_014817](https://github.com/RohitVerma882/termux-miunlock/assets/20979212/93ad7597-ccae-4290-8e77-5e6984d2f438)
![Screenshot_20230813-133045_Termux_014821](https://github.com/RohitVerma882/termux-miunlock/assets/20979212/d724f3ea-428d-445c-a9d3-2b70ecb345ba)
![Screenshot_2023-08-13-13-46-29-742_com android settings](https://github.com/RohitVerma882/termux-miunlock/assets/20979212/d5e067ea-5ee0-4e0d-9cba-c74896338f17)

**Comment by RohitVerma882** [comment]
Have you unlocked this device for the first time?

**Comment by ahmad24shargh** [comment]
Yes
I just bought it 2 weeks ago
I did not care about the 18-month quarantine.
I can only work with a rooted phone.

**Comment by IamBebi** [comment]
> Mulțumesc că a funcționat Telefonul meu este Redmi note 12 4g cu nume de cod tapas și ROM global. Prin adăugarea --region=global ..... În termux, comanda xxd nu este instalată implicit. L-am instalat cu următoarea comandă. pkg instalează vim-python .... ![Captură de ecran_20230813-132532_Termux_014817](https://private-user-images.githubusercontent.com/20979212/260297229-93ad7597-ccae-4290-8e77-5e6984d2f438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NjUzNzYsIm5iZiI6MTcwODg2NTA3NiwicGF0aCI6Ii8yMDk3OTIxMi8yNjAyOTcyMjktOTNhZDc1OTctY2NhZS00MjkwLThlNzctNWU2OTg0ZDJmNDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEyNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMjEzNjIyMDlhMDE2NWYzZjhiMTE3ZTQ3ODM0NWFhN2UxNDdlNzRiMThlN2IwYzE3OGUwZDg4MDBiM2VjNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h06iuOQID4clvvqO6IbhYPurdFRDrHv_XvBu7L54gBw) ![Captură de ecran_20230813-133045_Termux_014821](https://private-user-images.githubusercontent.com/20979212/260297239-d724f3ea-428d-445c-a9d3-2b70ecb345ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NjUzNzYsIm5iZiI6MTcwODg2NTA3NiwicGF0aCI6Ii8yMDk3OTIxMi8yNjAyOTcyMzktZDcyNGYzZWEtNDI4ZC00NDVjLWE5ZDMtMmI3MGVjYjM0NWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEyNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYjkyMzZmNTBhMGI1MWZlZTUwOTFjNzAyMTVjZWRiNTBhZjlkZjFlZGIzNzc1OTZjOTQ0YTFmMDgzMWM1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9-4MEBuCGGDivKVBLG86Ncn1yNd8fe6rhZ-3AjF6rFM) ![Captură de ecran_2023-08-13-13-46-29-742_com setări Android](https://private-user-images.githubusercontent.com/20979212/260297246-d5e067ea-5ee0-4e0d-9cba-c74896338f17.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NjUzNzYsIm5iZiI6MTcwODg2NTA3NiwicGF0aCI6Ii8yMDk3OTIxMi8yNjAyOTcyNDYtZDVlMDY3ZWEtNWVlMC00ZTBkLTljYmEtYzc0ODk2MzM4ZjE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEyNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NmEwOWEzNjg3M2QxOTVhMDlkNThhODZkOTQwOTA0YThiZDViZmU3NzJlNmFlYjFjNTc0MDYyNGUzMmY1YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uU0yJaaUkgR9m7VyqLqxnLRhYDnZTPZzVeOIJIW7nT0)

I have the same phone model and it doesn't work, please help. how did you do

**Comment by kurtdavidlol** [comment]
the instructions is literally right there. you have to add your mi account in settings > developer options > mi unlock status.. if you don't have a mi account already create one. keep in mind you have to enable developer options first or else it's just completely hidden
