### ISSUE TITLE
Err:0xffffffff' getting this error on last step 

### ISSUE THREAD

**Issue by iamcat007** [RohitVerma882/termux-miunlock#22]
Sending 'token' (0 KB)     OKAY [ 0.006s]

unlocking bootloader       FAILED (remote: 'Unlock failed - Err:0xffffffff')

fastboot: error: Command failed

https://i.imgur.com/9f4rDf4.jpg

And phone rebooted in system 
Same output with 
mi-fastboot stage token.bin && mi-fastboot oem unlock
&
 mi-fastboot oem-unlock "UNLOCK_TOKEN"

**Comment by RohitVerma882** [comment]
If it still doesn't fixed, try changing the Data cable.
