### ISSUE TITLE
mi unlock problem meadiatek devices

### ISSUE THREAD

**Issue by Aaaa07** [RohitVerma882/termux-miunlock#24]
hi sir,  mi bootloader  meadiatek devices commond not work  this commond is.

(mi-fastboot oem get token) please fix it

thank you.

**Comment by Aaaa07** [comment]
redmi 6a

**Comment by RohitVerma882** [comment]
```mi-fastboot oem get_token``` not working?

**Comment by RohitVerma882** [comment]
Give me more details and screenshot

**Comment by Aaaa07** [comment]
device redmi 6a

**Comment by Aaaa07** [comment]
> `mi-fastboot oem get_token` not working?

yes

**Comment by Whittobae6** [comment]
Redmi 10 2022 ,miui 14.0.4.0 TKUIDXM Eror 20031 sir

**Comment by Aaaa07** [comment]
Please help
