### ISSUE TITLE
Compatible with Xiaomi 14 Pro?

### ISSUE THREAD

**Issue by drphero** [RohitVerma882/termux-miunlock#29]
I'm considering buying a Xiaomi 14 Pro and would like to know if this unlock method will work on it.

**Comment by RohitVerma882** [comment]
Works on most devices

**Comment by drphero** [comment]
@RohitVerma882 By 'most devices', do you mean most Xiaomi devices in general, or most Xiaomi 14 Pro devices?

**Comment by drphero** [comment]
@RohitVerma882 As you may know, the Xiaomi 14 devices are a bit different with the HyperOS. Previous methods that worked on older devices seem to be failing with the latest ones. That's why I'm asking if you know of any success with the Xiaomi 14/14 Pro.

**Comment by RohitVerma882** [comment]
This tool is not work with HyperOS
