### ISSUE TITLE
May I ask some question?

### ISSUE THREAD

**Issue by DataEraserC** [RohitVerma882/termux-miunlock#3]
- Can the token.bin obtained using your program be reused?
- Do you have any plans to create a similar program for Linux? (I'm eager for it, but I don't want to pressure you into doing it) (Or is there an existing program that can accomplish this which I haven't found yet?)

**Comment by RohitVerma882** [comment]
1) Obtained token cannot be reused (also if device rebooted before unlock)
2)  No, for Linux use: https://github.com/francescotescari/XiaoMiToolV2
