### ISSUE TITLE
Everything correct but at the end getting a problem 

### ISSUE THREAD

**Issue by akhilbro1230** [RohitVerma882/termux-miunlock#31]
Sending 'token' (0 KB)                             OKAY [  0.002s]
unlocking bootloader                               FAILED (remote: 'Token Verify Failed, Reboot the device
')
fastboot: error: Command failed

ft.Poco M6 Pro 5G

**Comment by akhilbro1230** [comment]
> Old token can not be used again if your device rebooted before unlocking 

Please tell me what to do next

**Comment by RohitVerma882** [comment]
See #9

**Comment by akhilbro1230** [comment]
> See #9

Bruh,I have unlocked the bootloader and I'm getting bootloop why 😭

**Comment by RohitVerma882** [comment]
Bootloader unlocking is safe, i think you flashed anything unstable

**Comment by akhilbro1230** [comment]
Yes I was done something wrong, but Im go to an official Xiaomi Service
Center and with my warranty,they have fixed the issue for my mobile phone
