### ISSUE TITLE
Ask about region and host device

### ISSUE THREAD

**Issue by researchscum** [RohitVerma882/termux-miunlock#32]
target device:
POCO F3
MIUI 14.0.4.0 TKHIDXM
Abdroid 13

host device:
Samsung
One Ui 5.1
Android 13

1. get-token.sh => error 20045, there is no indonesia region available in readme, is it safe to type indonesia for region?
2. is there a chance for indonesia region added later?
3. is it okay to use samsung as a host?

honestly i already done the step until ./get_token.sh --region=REGION --product=PRODUCT --token=TOKEN DATA
using global for region
using samsung phone with locked bootloader as a host
i get the token for unlocking
but i realize the phone bought in indonesia, the rom indonesia.
when i come to this site again to check if there is indonesia region now and open issue tab, the top of the list ended with bootloop.
now i am a little concerned.
hope someone can assure me of my unfounded concern.

**Comment by RohitVerma882** [comment]
Try global region if you received unlock token though global region, its
safe to use, no problem
