### ISSUE TITLE
UnlockRequest.exec

### ISSUE THREAD

**Issue by Heartbreaker161801040916** [RohitVerma882/termux-miunlock#38]
Please reply soon
![IMG-20240103-WA0020](https://github.com/RohitVerma882/termux-miunlock/assets/126741385/43e0eab2-41a6-4dc1-a395-ceb35cee20ea)

**Comment by RohitVerma882** [comment]
Check your internet connection or try to change host region

**Comment by RohitVerma882** [comment]
I don't know what causes this error

**Comment by Heartbreaker161801040916** [comment]
Please look into it and confirm a suggestion

**Comment by Heartbreaker161801040916** [comment]
What to do! I am trying through 1 month but everytime it's has another new issue!

**Comment by RohitVerma882** [comment]
> > try `./get_token.sh --region=global --product=<product> --token=<token> <data>`
> 
> ![IMG-20240103-WA0023](https://private-user-images.githubusercontent.com/126741385/293986787-1742fbf1-1afb-4628-97f6-1ce5683f3262.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDM2NzIsIm5iZiI6MTcwNDMwMzM3MiwicGF0aCI6Ii8xMjY3NDEzODUvMjkzOTg2Nzg3LTE3NDJmYmYxLTFhZmItNDYyOC05N2Y2LTFjZTU2ODNmMzI2Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxNzM2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzNmMTU0MjQ0YmViMzRmYzY1ODIxOTI5ZTQ2NGQxZmZhYjkxNmIxYmMxMzViNThhZWY2NjM4ODY3MjFjODY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qCn3BYochXUyAE6APDZAbb4zjnG2VsK19M6VVRWJmek) ![IMG-20240103-WA0022](https://private-user-images.githubusercontent.com/126741385/293986820-4054fd78-2289-4dd2-8c7b-44420fe7c724.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDM2NzIsIm5iZiI6MTcwNDMwMzM3MiwicGF0aCI6Ii8xMjY3NDEzODUvMjkzOTg2ODIwLTQwNTRmZDc4LTIyODktNGRkMi04YzdiLTQ0NDIwZmU3YzcyNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxNzM2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzZmOGJiNmNmZTZiNTA5ODg4MzMxNDRlZjFmZTJmMmQ0M2YzOTkwOTE2MTNkYWMxMGUwNTllNmVhYWQ1NzVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TQtTQyO6HvERg_QPQibR2jWXi7pmg8pkvNDay_5RpYQ)

According to your screenshot ```global``` region is correct for your device

**Comment by RohitVerma882** [comment]
rebind your mi account and login same account to ```accoumt.apk```

**Comment by Heartbreaker161801040916** [comment]
But global take me here
![Uploading IMG-20240103-WA0023.jpg…]()

**Comment by Heartbreaker161801040916** [comment]
> rebind your mi account and login same account to `accoumt.apk`

But global take me here
![IMG-20240103-WA0023](https://github.com/RohitVerma882/termux-miunlock/assets/126741385/228da344-ef4d-4b4e-9153-df0ca69d9698)
Every time after bind and login!

**Comment by Heartbreaker161801040916** [comment]
Please give me exact direction to unlock bootloader

**Comment by Benjie35** [comment]
Sir how to unlock bootloader vivo y19
