### ISSUE TITLE
Brother, I encountered a problem in the last steps Missing required parameter: 'DATA'

### ISSUE THREAD

**Issue by Asfhd4** [RohitVerma882/termux-miunlock#42]
![Uploading Screenshot_٢٠٢٤-٠١-٢٥-٢١-١٩-٠٤-٥٦٢_com.miui.gallery.jpg…]()
![Screenshot_٢٠٢٤-٠١-٢٥-٢١-٢٤-٣٤-٦٠٠_com miui gallery](https://github.com/RohitVerma882/termux-miunlock/assets/157737556/c1e98e9d-7374-4f4f-af04-86e5e7203ef5)
![Screenshot_٢٠٢٤-٠١-٢٥-٢١-٢٤-٠٦-٥٥٦_com miui gallery](https://github.com/RohitVerma882/termux-miunlock/assets/157737556/c90cfb5c-a07c-4f6b-b914-87a26dce903f)

**Comment by RohitVerma882** [comment]
User token (data) is required, you're entered wrong data
