### ISSUE TITLE
Sending 'token' (0 KB) OK AY [ 0.006s] unlocking bootloader FA ILED (remote: 'Token Verify Failed, Reboot the device ') fastboot: error: Command failed

### ISSUE THREAD

**Issue by Jaskaransingh8427** [RohitVerma882/termux-miunlock#43]
How to fix this error I am using this tool for redmi note 7
![Screenshot_20240131_220611_Termux](https://github.com/RohitVerma882/termux-miunlock/assets/158231906/2a84f1e9-1cda-4527-a166-3bfe421c698b)

**Comment by RohitVerma882** [comment]
Remove old token.bin and try again
