### ISSUE TITLE
Not work on Redmi k70pro with HyperOS

### ISSUE THREAD

**Issue by feilongproject** [RohitVerma882/termux-miunlock#44]
On Redmi k70pro, it is necessary to verify before adding devices to the account. Is there any way to solve this problem?

![1706848752382](https://github.com/RohitVerma882/termux-miunlock/assets/43880786/505603ef-3880-4e8f-80cc-03d9e0e898fb)

**Comment by RohitVerma882** [comment]
You need to bind your xiaomi account before unlocking bootloader.

**Comment by RohitVerma882** [comment]
https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass

**Comment by feilongproject** [comment]
> You need to bind your xiaomi account before unlocking bootloader.在解锁引导加载程序之前，您需要绑定您的小米帐户。

It seems that the device cannot be bound due to being forced to verify the account. Is there any other way?
