### ISSUE TITLE
Not work man pls help me

### ISSUE THREAD

**Issue by IamBebi** [RohitVerma882/termux-miunlock#45]
![Screenshot_20240224_020438_Termux](https://github.com/RohitVerma882/termux-miunlock/assets/121450484/a3b9d6b8-b0d8-4ba9-851e-a0826c2622a9)

**Comment by RohitVerma882** [comment]
Read server message first

**Comment by IamBebi** [comment]
I associated the account 5 times and with the developer options and the problem still persists

**Comment by IamBebi** [comment]
I have a Redmi Note 10 phone Version MIUI 14.0.6 Global Stable Android 12 SKQ1.210908.001

**Comment by RohitVerma882** [comment]
Use same account for bind and unlock

**Comment by RohitVerma882** [comment]
Or try to change server region

**Comment by IamBebi** [comment]
I tried with global region but the same error always

**Comment by IamBebi** [comment]
Could you find out something to help me?

**Comment by IamBebi** [comment]
Am încercat cu toate regiunile

**Comment by IamBebi** [comment]
I tried with all regions and I still get the same error

**Comment by RohitVerma882** [comment]
see #49
