### ISSUE TITLE
"Is This Available in Ubuntu?"

### ISSUE THREAD

**Issue by cyberplaysv2** [RohitVerma882/termux-miunlock#51]
i don't have otg for this to work is this work on ubuntu?
![Screenshot from 2024-03-25 12-15-41](https://github.com/RohitVerma882/termux-miunlock/assets/82299606/114d099b-428a-491f-b494-1e23252f4b26)

**Comment by RohitVerma882** [comment]
> i don't have otg for this to work is this work on ubuntu? ![Screenshot from 2024-03-25 12-15-41](https://private-user-images.githubusercontent.com/82299606/316384705-114d099b-428a-491f-b494-1e23252f4b26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjA4NTEsIm5iZiI6MTcxMjEyMDU1MSwicGF0aCI6Ii84MjI5OTYwNi8zMTYzODQ3MDUtMTE0ZDA5OWItNDI4YS00OTFmLWI0OTQtMWUyMzI1MmY0YjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA1MDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NWQzMzBjYzExY2RjNDJiOGIzNzc0YjViNmM4M2ZmYzM3Nzg4ZmJjOGZlMGJlMzlhYzM1ODAwOWEwZTM4OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._xA9wh7rAX3Lf_mGEEXZ9UoncRF9_yXsQn144IPLL3g)

Try to install java-jdk & releted pkgs manually
