### ISSUE TITLE
Error occurred during initialization of VM

### ISSUE THREAD

**Issue by Ivestvieary** [RohitVerma882/termux-miunlock#52]
Error occurred during initialization of VM
Unable to load native library: dlopen failed: library "libandroid-spawn.so" not found

**Comment by Ivestvieary** [comment]
![IMG-20240402-WA0000.jpg](https://github.com/RohitVerma882/termux-miunlock/assets/165834996/bbd94ce1-e165-45ad-8921-7c318e58d3c4)

**Comment by Ivestvieary** [comment]
Please help me 🙏🙏🙏

**Comment by RohitVerma882** [comment]
> Please help me 🙏🙏🙏

Java jdk is not installed properly, clear termux data and reinstall again
