### ISSUE TITLE
Sending "token" (0 KB) OKAY [ 0.011s] unlocking bootloader FAILED (remote: "Token Verify Failed, Reboot the device fastboot: error: Command failed

### ISSUE THREAD

**Issue by BigL-Misfit** [RohitVerma882/termux-miunlock#65]
I successfully got the unlock token but it says "Token Verify Failed, Reboot the device". Any solution? 
![IMG-20240703-WA0001](https://github.com/RohitVerma882/termux-miunlock/assets/123742992/83d68e63-3fa0-483d-b86b-b254dc9cefdc)

**Comment by willkof2** [comment]
I have the same issue, still no solutions?

**Comment by sourav9242** [comment]
I have the sae issu

**Comment by atimsus** [comment]
I have the sae issue. Please give me solution

**Comment by RohitVerma882** [comment]
https://github.com/RohitVerma882/termux-miunlock/issues/9#issuecomment-1719929155
