### ISSUE TITLE
SEVERE: Xiaomi server returned error 20045:  Error description: Unknown error: 20045  Server description: Please use the common user tool on the official website

### ISSUE THREAD

**Issue by Uservx1** [RohitVerma882/termux-miunlock#73]
How can I solve this problem?

**Comment by Kaloyan501** [comment]
Your region is wrong, try another one. I had the same issue when giving the script that gets the key the argument global, I tried with europe and it worked. Just try to run the script will all regions (india, global, china, russia, europe) and see if it works.
