### ISSUE TITLE
"There was a problem parsing the package" on an old android

### ISSUE THREAD

**Issue by Ltutamen** [RohitVerma882/termux-miunlock#78]
I cannot install .apk on an Xiaomi pad 1 (xiaomi-mocha with android 4.4.4 ktu84p, miui global 7.5 | stable 7.5.2.0(KXFMIDE)), app instalation fails with "There was a problem parsing the package".

**Comment by RohitVerma882** [comment]
```account.apk``` supported on android 5+ devices.
