### ISSUE TITLE
Fastboot error in last command 

### ISSUE THREAD

**Issue by MDrifat1177** [RohitVerma882/termux-miunlock#9]
![GSjNcHJTDcOqdcZMSfwcNWBiOhB](https://github.com/RohitVerma882/termux-miunlock/assets/143925569/777c34b9-c90b-4e3f-95b1-88cc784a04e7)
 Love from Bangladesh please fix this issue last command
problem fastboot ADB install but ADB fastboot error please
Fix
![G2SnUThazdHdPRrgWqMjMHJTxqH](https://github.com/RohitVerma882/termux-miunlock/assets/143925569/048205d6-1b3f-4d2c-b408-9583ba9d46b6)

**Comment by RohitVerma882** [comment]
Delete the old token.bin file and generate it again from server

**Comment by MdRifat64986** [comment]
tanks for response my phone is unlocked love for Bangladesh 
![Screenshot_20230916-132014_Settings](https://github.com/RohitVerma882/termux-miunlock/assets/145187650/1a4c72f7-61ee-45b7-9360-ae18c00b685a)
![Screenshot_20230916-132006_Settings](https://github.com/RohitVerma882/termux-miunlock/assets/145187650/03f514e4-3bee-4cde-a94b-a190fdc59b53)
🥰🥰🥰

**Comment by iamcat007** [comment]
> if your phone rebooted before unlock or failed to unlock then you need to generate token again

Which token mi-fastboot oem get_token
Or server token?

**Comment by RohitVerma882** [comment]
Both
